#!/bin/bash

# 🏠 Homelab Dashboard - Quick Reference
# Copy this file for instant access to commands

echo "🏠 Homelab Dashboard - Quick Reference"
echo "======================================"
echo ""
echo "📋 INSTALLATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "chmod +x setup.sh && ./setup.sh"
echo ""
echo "🚀 DEVELOPMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "npm run dev              # Start both servers"
echo "npm run server:dev       # Backend only"
echo "npm run client:dev       # Frontend only"
echo ""
echo "📦 BUILD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "npm run build            # Build all"
echo "npm run server:build     # Build backend"
echo "npm run client:build     # Build frontend"
echo ""
echo "🐳 DOCKER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "npm run docker:up        # Start containers"
echo "npm run docker:down      # Stop containers"
echo ""
echo "🌐 ACCESS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Frontend:  http://localhost:3000"
echo "Backend:   http://localhost:5000"
echo "API Docs:  http://localhost:5000/api/health"
echo ""
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "README.md              - Full documentation"
echo "GETTING_STARTED.md     - Quick start"
echo "PROJECT_GUIDE.md       - Architecture"
echo "FEATURES.md            - Feature list"
echo "TROUBLESHOOTING.md     - Common issues"
echo ""
echo "🔧 ENVIRONMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ".env                   - Configuration"
echo ".env.example           - Template"
echo ""
echo "⚡ QUICK TROUBLESHOOT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Port 5000 in use:      Edit .env (PORT=5001)"
echo "Port 3000 in use:      Edit client/vite.config.ts"
echo "Database error:        rm homelab.db && npm run dev"
echo "Clear everything:      rm -rf node_modules && npm install"
echo ""
echo "✨ YOUR HOMELAB IS READY!"
echo "======================================"
